// ----------------------------------------------------------------------------
// File: TrafficShaping.proto
// Author: Luis Antonio Obis Aparicio <luis.obis@cern.ch>
// ----------------------------------------------------------------------------

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/TrafficShapingMonitor.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Eos_TrafficShapingRate_FullMethodName = "/eos.rpc.Eos/TrafficShapingRate"
)

// EosClient is the client API for Eos service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EosClient interface {
	TrafficShapingRate(ctx context.Context, in *TrafficShapingRateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TrafficShapingRateResponse], error)
}

type eosClient struct {
	cc grpc.ClientConnInterface
}

func NewEosClient(cc grpc.ClientConnInterface) EosClient {
	return &eosClient{cc}
}

func (c *eosClient) TrafficShapingRate(ctx context.Context, in *TrafficShapingRateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TrafficShapingRateResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Eos_ServiceDesc.Streams[0], Eos_TrafficShapingRate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TrafficShapingRateRequest, TrafficShapingRateResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Eos_TrafficShapingRateClient = grpc.ServerStreamingClient[TrafficShapingRateResponse]

// EosServer is the server API for Eos service.
// All implementations must embed UnimplementedEosServer
// for forward compatibility.
type EosServer interface {
	TrafficShapingRate(*TrafficShapingRateRequest, grpc.ServerStreamingServer[TrafficShapingRateResponse]) error
	mustEmbedUnimplementedEosServer()
}

// UnimplementedEosServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEosServer struct{}

func (UnimplementedEosServer) TrafficShapingRate(*TrafficShapingRateRequest, grpc.ServerStreamingServer[TrafficShapingRateResponse]) error {
	return status.Error(codes.Unimplemented, "method TrafficShapingRate not implemented")
}
func (UnimplementedEosServer) mustEmbedUnimplementedEosServer() {}
func (UnimplementedEosServer) testEmbeddedByValue()             {}

// UnsafeEosServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EosServer will
// result in compilation errors.
type UnsafeEosServer interface {
	mustEmbedUnimplementedEosServer()
}

func RegisterEosServer(s grpc.ServiceRegistrar, srv EosServer) {
	// If the following call panics, it indicates UnimplementedEosServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Eos_ServiceDesc, srv)
}

func _Eos_TrafficShapingRate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TrafficShapingRateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EosServer).TrafficShapingRate(m, &grpc.GenericServerStream[TrafficShapingRateRequest, TrafficShapingRateResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Eos_TrafficShapingRateServer = grpc.ServerStreamingServer[TrafficShapingRateResponse]

// Eos_ServiceDesc is the grpc.ServiceDesc for Eos service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Eos_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "eos.rpc.Eos",
	HandlerType: (*EosServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TrafficShapingRate",
			Handler:       _Eos_TrafficShapingRate_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/TrafficShapingMonitor.proto",
}
