// ----------------------------------------------------------------------------
// File: TrafficShaping.proto
// Author: Luis Antonio Obis Aparicio <luis.obis@cern.ch>
// ----------------------------------------------------------------------------

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/TrafficShaping.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RateRequest_Estimators int32

const (
	RateRequest_UNSPECIFIED RateRequest_Estimators = 0 // Proto3 best practice (default 0 should be no-op)
	// SMA
	RateRequest_SMA_5_SECONDS RateRequest_Estimators = 1
	RateRequest_SMA_1_MINUTES RateRequest_Estimators = 2
	RateRequest_SMA_5_MINUTES RateRequest_Estimators = 3
	// EMA
	RateRequest_EMA_5_SECONDS RateRequest_Estimators = 4
	RateRequest_EMA_1_MINUTES RateRequest_Estimators = 5
	RateRequest_EMA_5_MINUTES RateRequest_Estimators = 6
)

// Enum value maps for RateRequest_Estimators.
var (
	RateRequest_Estimators_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "SMA_5_SECONDS",
		2: "SMA_1_MINUTES",
		3: "SMA_5_MINUTES",
		4: "EMA_5_SECONDS",
		5: "EMA_1_MINUTES",
		6: "EMA_5_MINUTES",
	}
	RateRequest_Estimators_value = map[string]int32{
		"UNSPECIFIED":   0,
		"SMA_5_SECONDS": 1,
		"SMA_1_MINUTES": 2,
		"SMA_5_MINUTES": 3,
		"EMA_5_SECONDS": 4,
		"EMA_1_MINUTES": 5,
		"EMA_5_MINUTES": 6,
	}
)

func (x RateRequest_Estimators) Enum() *RateRequest_Estimators {
	p := new(RateRequest_Estimators)
	*p = x
	return p
}

func (x RateRequest_Estimators) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RateRequest_Estimators) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_TrafficShaping_proto_enumTypes[0].Descriptor()
}

func (RateRequest_Estimators) Type() protoreflect.EnumType {
	return &file_proto_TrafficShaping_proto_enumTypes[0]
}

func (x RateRequest_Estimators) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RateRequest_Estimators.Descriptor instead.
func (RateRequest_Estimators) EnumDescriptor() ([]byte, []int) {
	return file_proto_TrafficShaping_proto_rawDescGZIP(), []int{7, 0}
}

type RateRequest_EntityType int32

const (
	RateRequest_ENTITY_UNSPECIFIED RateRequest_EntityType = 0
	RateRequest_ENTITY_APP         RateRequest_EntityType = 1
	RateRequest_ENTITY_UID         RateRequest_EntityType = 2
	RateRequest_ENTITY_GID         RateRequest_EntityType = 3
)

// Enum value maps for RateRequest_EntityType.
var (
	RateRequest_EntityType_name = map[int32]string{
		0: "ENTITY_UNSPECIFIED",
		1: "ENTITY_APP",
		2: "ENTITY_UID",
		3: "ENTITY_GID",
	}
	RateRequest_EntityType_value = map[string]int32{
		"ENTITY_UNSPECIFIED": 0,
		"ENTITY_APP":         1,
		"ENTITY_UID":         2,
		"ENTITY_GID":         3,
	}
)

func (x RateRequest_EntityType) Enum() *RateRequest_EntityType {
	p := new(RateRequest_EntityType)
	*p = x
	return p
}

func (x RateRequest_EntityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RateRequest_EntityType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_TrafficShaping_proto_enumTypes[1].Descriptor()
}

func (RateRequest_EntityType) Type() protoreflect.EnumType {
	return &file_proto_TrafficShaping_proto_enumTypes[1]
}

func (x RateRequest_EntityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RateRequest_EntityType.Descriptor instead.
func (RateRequest_EntityType) EnumDescriptor() ([]byte, []int) {
	return file_proto_TrafficShaping_proto_rawDescGZIP(), []int{7, 1}
}

// Represents the I/O stats for a single "Stream" (Unique App/UID/GID combo).
// This is only sent if the counters have changed since the last report.
type IoStatEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// --- Identity ---
	// The application name (e.g., "backup_daemon", "chrome").
	// TODO: Consider mapping this to an int32 ID in a separate dictionary if string overhead is too high.
	AppName string `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Uid     uint32 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"` // The user ID
	Gid     uint32 `protobuf:"varint,3,opt,name=gid,proto3" json:"gid,omitempty"` // The group ID
	// --- Lifecycle Safety ---
	// A unique random ID generated when this counter was created in the Node's memory.
	// CRITICAL: If the Node garbage collects this entry and recreates it later (starting from 0),
	// this ID MUST change. This tells the Brain "This is a new session, do not diff against old value."
	GenerationId uint64 `protobuf:"varint,4,opt,name=generation_id,json=generationId,proto3" json:"generation_id,omitempty"`
	// --- Metrics (Cumulative) ---
	// We use cumulative counters to be robust against packet loss.
	// The Brain calculates: Delta = Current - Previous.
	TotalBytesRead    uint64 `protobuf:"varint,5,opt,name=total_bytes_read,json=totalBytesRead,proto3" json:"total_bytes_read,omitempty"`
	TotalBytesWritten uint64 `protobuf:"varint,6,opt,name=total_bytes_written,json=totalBytesWritten,proto3" json:"total_bytes_written,omitempty"`
	// IOPS
	TotalReadOps  uint64 `protobuf:"varint,7,opt,name=total_read_ops,json=totalReadOps,proto3" json:"total_read_ops,omitempty"`
	TotalWriteOps uint64 `protobuf:"varint,8,opt,name=total_write_ops,json=totalWriteOps,proto3" json:"total_write_ops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IoStatEntry) Reset() {
	*x = IoStatEntry{}
	mi := &file_proto_TrafficShaping_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IoStatEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IoStatEntry) ProtoMessage() {}

func (x *IoStatEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_TrafficShaping_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IoStatEntry.ProtoReflect.Descriptor instead.
func (*IoStatEntry) Descriptor() ([]byte, []int) {
	return file_proto_TrafficShaping_proto_rawDescGZIP(), []int{0}
}

func (x *IoStatEntry) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *IoStatEntry) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *IoStatEntry) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *IoStatEntry) GetGenerationId() uint64 {
	if x != nil {
		return x.GenerationId
	}
	return 0
}

func (x *IoStatEntry) GetTotalBytesRead() uint64 {
	if x != nil {
		return x.TotalBytesRead
	}
	return 0
}

func (x *IoStatEntry) GetTotalBytesWritten() uint64 {
	if x != nil {
		return x.TotalBytesWritten
	}
	return 0
}

func (x *IoStatEntry) GetTotalReadOps() uint64 {
	if x != nil {
		return x.TotalReadOps
	}
	return 0
}

func (x *IoStatEntry) GetTotalWriteOps() uint64 {
	if x != nil {
		return x.TotalWriteOps
	}
	return 0
}

// The heartbeat message sent every 1 second by every Storage Node.
type FstIoReport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// --- Metadata ---
	NodeId      string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                 // Unique Hostname or UUID of the FST
	TimestampMs int64  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"` // When this snapshot was taken (Unix Epoch)
	// To detect Node Restarts. If this changes, MGM discards all previous state for this Node.
	NodeStartTimeMs int64 `protobuf:"varint,3,opt,name=node_start_time_ms,json=nodeStartTimeMs,proto3" json:"node_start_time_ms,omitempty"`
	// --- Payload ---
	// List of streams that have activity. Idle streams are omitted to save bandwidth.
	Entries       []*IoStatEntry `protobuf:"bytes,4,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FstIoReport) Reset() {
	*x = FstIoReport{}
	mi := &file_proto_TrafficShaping_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FstIoReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FstIoReport) ProtoMessage() {}

func (x *FstIoReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_TrafficShaping_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FstIoReport.ProtoReflect.Descriptor instead.
func (*FstIoReport) Descriptor() ([]byte, []int) {
	return file_proto_TrafficShaping_proto_rawDescGZIP(), []int{1}
}

func (x *FstIoReport) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *FstIoReport) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *FstIoReport) GetNodeStartTimeMs() int64 {
	if x != nil {
		return x.NodeStartTimeMs
	}
	return 0
}

func (x *FstIoReport) GetEntries() []*IoStatEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type MgmIoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// We will fill this with rate-limit instructions later.
	// For now, it can just acknowledge receipt.
	Ack           bool `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MgmIoResponse) Reset() {
	*x = MgmIoResponse{}
	mi := &file_proto_TrafficShaping_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MgmIoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MgmIoResponse) ProtoMessage() {}

func (x *MgmIoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_TrafficShaping_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MgmIoResponse.ProtoReflect.Descriptor instead.
func (*MgmIoResponse) Descriptor() ([]byte, []int) {
	return file_proto_TrafficShaping_proto_rawDescGZIP(), []int{2}
}

func (x *MgmIoResponse) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

type RateStats struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Window             RateRequest_Estimators `protobuf:"varint,1,opt,name=window,proto3,enum=eos.traffic_shaping.RateRequest_Estimators" json:"window,omitempty"`
	BytesReadPerSec    float64                `protobuf:"fixed64,2,opt,name=bytes_read_per_sec,json=bytesReadPerSec,proto3" json:"bytes_read_per_sec,omitempty"`
	BytesWrittenPerSec float64                `protobuf:"fixed64,3,opt,name=bytes_written_per_sec,json=bytesWrittenPerSec,proto3" json:"bytes_written_per_sec,omitempty"`
	IopsRead           float64                `protobuf:"fixed64,4,opt,name=iops_read,json=iopsRead,proto3" json:"iops_read,omitempty"`
	IopsWrite          float64                `protobuf:"fixed64,5,opt,name=iops_write,json=iopsWrite,proto3" json:"iops_write,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RateStats) Reset() {
	*x = RateStats{}
	mi := &file_proto_TrafficShaping_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateStats) ProtoMessage() {}

func (x *RateStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_TrafficShaping_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateStats.ProtoReflect.Descriptor instead.
func (*RateStats) Descriptor() ([]byte, []int) {
	return file_proto_TrafficShaping_proto_rawDescGZIP(), []int{3}
}

func (x *RateStats) GetWindow() RateRequest_Estimators {
	if x != nil {
		return x.Window
	}
	return RateRequest_UNSPECIFIED
}

func (x *RateStats) GetBytesReadPerSec() float64 {
	if x != nil {
		return x.BytesReadPerSec
	}
	return 0
}

func (x *RateStats) GetBytesWrittenPerSec() float64 {
	if x != nil {
		return x.BytesWrittenPerSec
	}
	return 0
}

func (x *RateStats) GetIopsRead() float64 {
	if x != nil {
		return x.IopsRead
	}
	return 0
}

func (x *RateStats) GetIopsWrite() float64 {
	if x != nil {
		return x.IopsWrite
	}
	return 0
}

type AppRateEntry struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	AppName string                 `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	// CHANGE THIS: Add 'repeated'
	Stats         []*RateStats `protobuf:"bytes,2,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppRateEntry) Reset() {
	*x = AppRateEntry{}
	mi := &file_proto_TrafficShaping_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppRateEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppRateEntry) ProtoMessage() {}

func (x *AppRateEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_TrafficShaping_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppRateEntry.ProtoReflect.Descriptor instead.
func (*AppRateEntry) Descriptor() ([]byte, []int) {
	return file_proto_TrafficShaping_proto_rawDescGZIP(), []int{4}
}

func (x *AppRateEntry) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *AppRateEntry) GetStats() []*RateStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type UserRateEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Uid   uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// CHANGE THIS: Add 'repeated'
	Stats         []*RateStats `protobuf:"bytes,2,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRateEntry) Reset() {
	*x = UserRateEntry{}
	mi := &file_proto_TrafficShaping_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRateEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRateEntry) ProtoMessage() {}

func (x *UserRateEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_TrafficShaping_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRateEntry.ProtoReflect.Descriptor instead.
func (*UserRateEntry) Descriptor() ([]byte, []int) {
	return file_proto_TrafficShaping_proto_rawDescGZIP(), []int{5}
}

func (x *UserRateEntry) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UserRateEntry) GetStats() []*RateStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type GroupRateEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Gid   uint32                 `protobuf:"varint,1,opt,name=gid,proto3" json:"gid,omitempty"`
	// CHANGE THIS: Add 'repeated'
	Stats         []*RateStats `protobuf:"bytes,2,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupRateEntry) Reset() {
	*x = GroupRateEntry{}
	mi := &file_proto_TrafficShaping_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupRateEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupRateEntry) ProtoMessage() {}

func (x *GroupRateEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_TrafficShaping_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupRateEntry.ProtoReflect.Descriptor instead.
func (*GroupRateEntry) Descriptor() ([]byte, []int) {
	return file_proto_TrafficShaping_proto_rawDescGZIP(), []int{6}
}

func (x *GroupRateEntry) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *GroupRateEntry) GetStats() []*RateStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type RateRequest struct {
	state        protoimpl.MessageState   `protogen:"open.v1"`
	Estimators   []RateRequest_Estimators `protobuf:"varint,1,rep,packed,name=estimators,proto3,enum=eos.traffic_shaping.RateRequest_Estimators" json:"estimators,omitempty"`
	IncludeTypes []RateRequest_EntityType `protobuf:"varint,2,rep,packed,name=include_types,json=includeTypes,proto3,enum=eos.traffic_shaping.RateRequest_EntityType" json:"include_types,omitempty"`
	// How many top entries to return for each type? (e.g., Top 10 apps)
	TopN *uint32 `protobuf:"varint,3,opt,name=top_n,json=topN,proto3,oneof" json:"top_n,omitempty"`
	// --- 4. Sorting Ambiguity Resolver ---
	// If I ask for 5s and 5m windows, which one determines who is in the "Top 10"?
	// (e.g., Sort by 5m trend, but show me the 1s spikes too)
	SortByEstimator *RateRequest_Estimators `protobuf:"varint,4,opt,name=sort_by_estimator,json=sortByEstimator,proto3,enum=eos.traffic_shaping.RateRequest_Estimators,oneof" json:"sort_by_estimator,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RateRequest) Reset() {
	*x = RateRequest{}
	mi := &file_proto_TrafficShaping_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateRequest) ProtoMessage() {}

func (x *RateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_TrafficShaping_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateRequest.ProtoReflect.Descriptor instead.
func (*RateRequest) Descriptor() ([]byte, []int) {
	return file_proto_TrafficShaping_proto_rawDescGZIP(), []int{7}
}

func (x *RateRequest) GetEstimators() []RateRequest_Estimators {
	if x != nil {
		return x.Estimators
	}
	return nil
}

func (x *RateRequest) GetIncludeTypes() []RateRequest_EntityType {
	if x != nil {
		return x.IncludeTypes
	}
	return nil
}

func (x *RateRequest) GetTopN() uint32 {
	if x != nil && x.TopN != nil {
		return *x.TopN
	}
	return 0
}

func (x *RateRequest) GetSortByEstimator() RateRequest_Estimators {
	if x != nil && x.SortByEstimator != nil {
		return *x.SortByEstimator
	}
	return RateRequest_UNSPECIFIED
}

type RateReport struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	// These are only filled if requested in RateRequest
	AppStats      []*AppRateEntry   `protobuf:"bytes,2,rep,name=app_stats,json=appStats,proto3" json:"app_stats,omitempty"`
	UserStats     []*UserRateEntry  `protobuf:"bytes,3,rep,name=user_stats,json=userStats,proto3" json:"user_stats,omitempty"`
	GroupStats    []*GroupRateEntry `protobuf:"bytes,4,rep,name=group_stats,json=groupStats,proto3" json:"group_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateReport) Reset() {
	*x = RateReport{}
	mi := &file_proto_TrafficShaping_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateReport) ProtoMessage() {}

func (x *RateReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_TrafficShaping_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateReport.ProtoReflect.Descriptor instead.
func (*RateReport) Descriptor() ([]byte, []int) {
	return file_proto_TrafficShaping_proto_rawDescGZIP(), []int{8}
}

func (x *RateReport) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *RateReport) GetAppStats() []*AppRateEntry {
	if x != nil {
		return x.AppStats
	}
	return nil
}

func (x *RateReport) GetUserStats() []*UserRateEntry {
	if x != nil {
		return x.UserStats
	}
	return nil
}

func (x *RateReport) GetGroupStats() []*GroupRateEntry {
	if x != nil {
		return x.GroupStats
	}
	return nil
}

var File_proto_TrafficShaping_proto protoreflect.FileDescriptor

const file_proto_TrafficShaping_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/TrafficShaping.proto\x12\x13eos.traffic_shaping\"\x99\x02\n" +
	"\vIoStatEntry\x12\x19\n" +
	"\bapp_name\x18\x01 \x01(\tR\aappName\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\x03 \x01(\rR\x03gid\x12#\n" +
	"\rgeneration_id\x18\x04 \x01(\x04R\fgenerationId\x12(\n" +
	"\x10total_bytes_read\x18\x05 \x01(\x04R\x0etotalBytesRead\x12.\n" +
	"\x13total_bytes_written\x18\x06 \x01(\x04R\x11totalBytesWritten\x12$\n" +
	"\x0etotal_read_ops\x18\a \x01(\x04R\ftotalReadOps\x12&\n" +
	"\x0ftotal_write_ops\x18\b \x01(\x04R\rtotalWriteOps\"\xb2\x01\n" +
	"\vFstIoReport\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x12+\n" +
	"\x12node_start_time_ms\x18\x03 \x01(\x03R\x0fnodeStartTimeMs\x12:\n" +
	"\aentries\x18\x04 \x03(\v2 .eos.traffic_shaping.IoStatEntryR\aentries\"!\n" +
	"\rMgmIoResponse\x12\x10\n" +
	"\x03ack\x18\x01 \x01(\bR\x03ack\"\xec\x01\n" +
	"\tRateStats\x12C\n" +
	"\x06window\x18\x01 \x01(\x0e2+.eos.traffic_shaping.RateRequest.EstimatorsR\x06window\x12+\n" +
	"\x12bytes_read_per_sec\x18\x02 \x01(\x01R\x0fbytesReadPerSec\x121\n" +
	"\x15bytes_written_per_sec\x18\x03 \x01(\x01R\x12bytesWrittenPerSec\x12\x1b\n" +
	"\tiops_read\x18\x04 \x01(\x01R\biopsRead\x12\x1d\n" +
	"\n" +
	"iops_write\x18\x05 \x01(\x01R\tiopsWrite\"_\n" +
	"\fAppRateEntry\x12\x19\n" +
	"\bapp_name\x18\x01 \x01(\tR\aappName\x124\n" +
	"\x05stats\x18\x02 \x03(\v2\x1e.eos.traffic_shaping.RateStatsR\x05stats\"W\n" +
	"\rUserRateEntry\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\x124\n" +
	"\x05stats\x18\x02 \x03(\v2\x1e.eos.traffic_shaping.RateStatsR\x05stats\"X\n" +
	"\x0eGroupRateEntry\x12\x10\n" +
	"\x03gid\x18\x01 \x01(\rR\x03gid\x124\n" +
	"\x05stats\x18\x02 \x03(\v2\x1e.eos.traffic_shaping.RateStatsR\x05stats\"\xac\x04\n" +
	"\vRateRequest\x12K\n" +
	"\n" +
	"estimators\x18\x01 \x03(\x0e2+.eos.traffic_shaping.RateRequest.EstimatorsR\n" +
	"estimators\x12P\n" +
	"\rinclude_types\x18\x02 \x03(\x0e2+.eos.traffic_shaping.RateRequest.EntityTypeR\fincludeTypes\x12\x18\n" +
	"\x05top_n\x18\x03 \x01(\rH\x00R\x04topN\x88\x01\x01\x12\\\n" +
	"\x11sort_by_estimator\x18\x04 \x01(\x0e2+.eos.traffic_shaping.RateRequest.EstimatorsH\x01R\x0fsortByEstimator\x88\x01\x01\"\x8f\x01\n" +
	"\n" +
	"Estimators\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSMA_5_SECONDS\x10\x01\x12\x11\n" +
	"\rSMA_1_MINUTES\x10\x02\x12\x11\n" +
	"\rSMA_5_MINUTES\x10\x03\x12\x11\n" +
	"\rEMA_5_SECONDS\x10\x04\x12\x11\n" +
	"\rEMA_1_MINUTES\x10\x05\x12\x11\n" +
	"\rEMA_5_MINUTES\x10\x06\"T\n" +
	"\n" +
	"EntityType\x12\x16\n" +
	"\x12ENTITY_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"ENTITY_APP\x10\x01\x12\x0e\n" +
	"\n" +
	"ENTITY_UID\x10\x02\x12\x0e\n" +
	"\n" +
	"ENTITY_GID\x10\x03B\b\n" +
	"\x06_top_nB\x14\n" +
	"\x12_sort_by_estimator\"\xf8\x01\n" +
	"\n" +
	"RateReport\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\x12>\n" +
	"\tapp_stats\x18\x02 \x03(\v2!.eos.traffic_shaping.AppRateEntryR\bappStats\x12A\n" +
	"\n" +
	"user_stats\x18\x03 \x03(\v2\".eos.traffic_shaping.UserRateEntryR\tuserStats\x12D\n" +
	"\vgroup_stats\x18\x04 \x03(\v2#.eos.traffic_shaping.GroupRateEntryR\n" +
	"groupStats2r\n" +
	"\x15TrafficShapingService\x12Y\n" +
	"\rStreamIoStats\x12 .eos.traffic_shaping.FstIoReport\x1a\".eos.traffic_shaping.MgmIoResponse(\x010\x012\xb9\x01\n" +
	"\x14RateReportingService\x12M\n" +
	"\bGetRates\x12 .eos.traffic_shaping.RateRequest\x1a\x1f.eos.traffic_shaping.RateReport\x12R\n" +
	"\vStreamRates\x12 .eos.traffic_shaping.RateRequest\x1a\x1f.eos.traffic_shaping.RateReport0\x01B#Z!eos_traffic_shaping_monitor/protob\x06proto3"

var (
	file_proto_TrafficShaping_proto_rawDescOnce sync.Once
	file_proto_TrafficShaping_proto_rawDescData []byte
)

func file_proto_TrafficShaping_proto_rawDescGZIP() []byte {
	file_proto_TrafficShaping_proto_rawDescOnce.Do(func() {
		file_proto_TrafficShaping_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_TrafficShaping_proto_rawDesc), len(file_proto_TrafficShaping_proto_rawDesc)))
	})
	return file_proto_TrafficShaping_proto_rawDescData
}

var file_proto_TrafficShaping_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_TrafficShaping_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_TrafficShaping_proto_goTypes = []any{
	(RateRequest_Estimators)(0), // 0: eos.traffic_shaping.RateRequest.Estimators
	(RateRequest_EntityType)(0), // 1: eos.traffic_shaping.RateRequest.EntityType
	(*IoStatEntry)(nil),         // 2: eos.traffic_shaping.IoStatEntry
	(*FstIoReport)(nil),         // 3: eos.traffic_shaping.FstIoReport
	(*MgmIoResponse)(nil),       // 4: eos.traffic_shaping.MgmIoResponse
	(*RateStats)(nil),           // 5: eos.traffic_shaping.RateStats
	(*AppRateEntry)(nil),        // 6: eos.traffic_shaping.AppRateEntry
	(*UserRateEntry)(nil),       // 7: eos.traffic_shaping.UserRateEntry
	(*GroupRateEntry)(nil),      // 8: eos.traffic_shaping.GroupRateEntry
	(*RateRequest)(nil),         // 9: eos.traffic_shaping.RateRequest
	(*RateReport)(nil),          // 10: eos.traffic_shaping.RateReport
}
var file_proto_TrafficShaping_proto_depIdxs = []int32{
	2,  // 0: eos.traffic_shaping.FstIoReport.entries:type_name -> eos.traffic_shaping.IoStatEntry
	0,  // 1: eos.traffic_shaping.RateStats.window:type_name -> eos.traffic_shaping.RateRequest.Estimators
	5,  // 2: eos.traffic_shaping.AppRateEntry.stats:type_name -> eos.traffic_shaping.RateStats
	5,  // 3: eos.traffic_shaping.UserRateEntry.stats:type_name -> eos.traffic_shaping.RateStats
	5,  // 4: eos.traffic_shaping.GroupRateEntry.stats:type_name -> eos.traffic_shaping.RateStats
	0,  // 5: eos.traffic_shaping.RateRequest.estimators:type_name -> eos.traffic_shaping.RateRequest.Estimators
	1,  // 6: eos.traffic_shaping.RateRequest.include_types:type_name -> eos.traffic_shaping.RateRequest.EntityType
	0,  // 7: eos.traffic_shaping.RateRequest.sort_by_estimator:type_name -> eos.traffic_shaping.RateRequest.Estimators
	6,  // 8: eos.traffic_shaping.RateReport.app_stats:type_name -> eos.traffic_shaping.AppRateEntry
	7,  // 9: eos.traffic_shaping.RateReport.user_stats:type_name -> eos.traffic_shaping.UserRateEntry
	8,  // 10: eos.traffic_shaping.RateReport.group_stats:type_name -> eos.traffic_shaping.GroupRateEntry
	3,  // 11: eos.traffic_shaping.TrafficShapingService.StreamIoStats:input_type -> eos.traffic_shaping.FstIoReport
	9,  // 12: eos.traffic_shaping.RateReportingService.GetRates:input_type -> eos.traffic_shaping.RateRequest
	9,  // 13: eos.traffic_shaping.RateReportingService.StreamRates:input_type -> eos.traffic_shaping.RateRequest
	4,  // 14: eos.traffic_shaping.TrafficShapingService.StreamIoStats:output_type -> eos.traffic_shaping.MgmIoResponse
	10, // 15: eos.traffic_shaping.RateReportingService.GetRates:output_type -> eos.traffic_shaping.RateReport
	10, // 16: eos.traffic_shaping.RateReportingService.StreamRates:output_type -> eos.traffic_shaping.RateReport
	14, // [14:17] is the sub-list for method output_type
	11, // [11:14] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_TrafficShaping_proto_init() }
func file_proto_TrafficShaping_proto_init() {
	if File_proto_TrafficShaping_proto != nil {
		return
	}
	file_proto_TrafficShaping_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_TrafficShaping_proto_rawDesc), len(file_proto_TrafficShaping_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_TrafficShaping_proto_goTypes,
		DependencyIndexes: file_proto_TrafficShaping_proto_depIdxs,
		EnumInfos:         file_proto_TrafficShaping_proto_enumTypes,
		MessageInfos:      file_proto_TrafficShaping_proto_msgTypes,
	}.Build()
	File_proto_TrafficShaping_proto = out.File
	file_proto_TrafficShaping_proto_goTypes = nil
	file_proto_TrafficShaping_proto_depIdxs = nil
}
