// ----------------------------------------------------------------------------
// File: TrafficShaping.proto
// Author: Luis Antonio Obis Aparicio <luis.obis@cern.ch>
// ----------------------------------------------------------------------------

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/TrafficShapingMonitor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrafficShapingRateRequest_Estimators int32

const (
	TrafficShapingRateRequest_UNSPECIFIED TrafficShapingRateRequest_Estimators = 0 // Proto3 best practice (default 0 should be no-op)
	// SMA
	TrafficShapingRateRequest_SMA_5_SECONDS TrafficShapingRateRequest_Estimators = 1
	TrafficShapingRateRequest_SMA_1_MINUTES TrafficShapingRateRequest_Estimators = 2
	TrafficShapingRateRequest_SMA_5_MINUTES TrafficShapingRateRequest_Estimators = 3
	// EMA
	TrafficShapingRateRequest_EMA_5_SECONDS TrafficShapingRateRequest_Estimators = 4
	TrafficShapingRateRequest_EMA_1_MINUTES TrafficShapingRateRequest_Estimators = 5
	TrafficShapingRateRequest_EMA_5_MINUTES TrafficShapingRateRequest_Estimators = 6
)

// Enum value maps for TrafficShapingRateRequest_Estimators.
var (
	TrafficShapingRateRequest_Estimators_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "SMA_5_SECONDS",
		2: "SMA_1_MINUTES",
		3: "SMA_5_MINUTES",
		4: "EMA_5_SECONDS",
		5: "EMA_1_MINUTES",
		6: "EMA_5_MINUTES",
	}
	TrafficShapingRateRequest_Estimators_value = map[string]int32{
		"UNSPECIFIED":   0,
		"SMA_5_SECONDS": 1,
		"SMA_1_MINUTES": 2,
		"SMA_5_MINUTES": 3,
		"EMA_5_SECONDS": 4,
		"EMA_1_MINUTES": 5,
		"EMA_5_MINUTES": 6,
	}
)

func (x TrafficShapingRateRequest_Estimators) Enum() *TrafficShapingRateRequest_Estimators {
	p := new(TrafficShapingRateRequest_Estimators)
	*p = x
	return p
}

func (x TrafficShapingRateRequest_Estimators) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrafficShapingRateRequest_Estimators) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_TrafficShapingMonitor_proto_enumTypes[0].Descriptor()
}

func (TrafficShapingRateRequest_Estimators) Type() protoreflect.EnumType {
	return &file_proto_TrafficShapingMonitor_proto_enumTypes[0]
}

func (x TrafficShapingRateRequest_Estimators) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrafficShapingRateRequest_Estimators.Descriptor instead.
func (TrafficShapingRateRequest_Estimators) EnumDescriptor() ([]byte, []int) {
	return file_proto_TrafficShapingMonitor_proto_rawDescGZIP(), []int{0, 0}
}

type TrafficShapingRateRequest_EntityType int32

const (
	TrafficShapingRateRequest_ENTITY_UNSPECIFIED TrafficShapingRateRequest_EntityType = 0
	TrafficShapingRateRequest_ENTITY_APP         TrafficShapingRateRequest_EntityType = 1
	TrafficShapingRateRequest_ENTITY_UID         TrafficShapingRateRequest_EntityType = 2
	TrafficShapingRateRequest_ENTITY_GID         TrafficShapingRateRequest_EntityType = 3
)

// Enum value maps for TrafficShapingRateRequest_EntityType.
var (
	TrafficShapingRateRequest_EntityType_name = map[int32]string{
		0: "ENTITY_UNSPECIFIED",
		1: "ENTITY_APP",
		2: "ENTITY_UID",
		3: "ENTITY_GID",
	}
	TrafficShapingRateRequest_EntityType_value = map[string]int32{
		"ENTITY_UNSPECIFIED": 0,
		"ENTITY_APP":         1,
		"ENTITY_UID":         2,
		"ENTITY_GID":         3,
	}
)

func (x TrafficShapingRateRequest_EntityType) Enum() *TrafficShapingRateRequest_EntityType {
	p := new(TrafficShapingRateRequest_EntityType)
	*p = x
	return p
}

func (x TrafficShapingRateRequest_EntityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrafficShapingRateRequest_EntityType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_TrafficShapingMonitor_proto_enumTypes[1].Descriptor()
}

func (TrafficShapingRateRequest_EntityType) Type() protoreflect.EnumType {
	return &file_proto_TrafficShapingMonitor_proto_enumTypes[1]
}

func (x TrafficShapingRateRequest_EntityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrafficShapingRateRequest_EntityType.Descriptor instead.
func (TrafficShapingRateRequest_EntityType) EnumDescriptor() ([]byte, []int) {
	return file_proto_TrafficShapingMonitor_proto_rawDescGZIP(), []int{0, 1}
}

type TrafficShapingRateRequest struct {
	state        protoimpl.MessageState                 `protogen:"open.v1"`
	Estimators   []TrafficShapingRateRequest_Estimators `protobuf:"varint,1,rep,packed,name=estimators,proto3,enum=eos.traffic_shaping.TrafficShapingRateRequest_Estimators" json:"estimators,omitempty"`
	IncludeTypes []TrafficShapingRateRequest_EntityType `protobuf:"varint,2,rep,packed,name=include_types,json=includeTypes,proto3,enum=eos.traffic_shaping.TrafficShapingRateRequest_EntityType" json:"include_types,omitempty"`
	// How many top entries to return for each type? (e.g., Top 10 apps)
	TopN *uint32 `protobuf:"varint,3,opt,name=top_n,json=topN,proto3,oneof" json:"top_n,omitempty"`
	// --- 4. Sorting Ambiguity Resolver ---
	// If I ask for 5s and 5m windows, which one determines who is in the "Top 10"?
	// (e.g., Sort by 5m trend, but show me the 1s spikes too)
	SortByEstimator *TrafficShapingRateRequest_Estimators `protobuf:"varint,4,opt,name=sort_by_estimator,json=sortByEstimator,proto3,enum=eos.traffic_shaping.TrafficShapingRateRequest_Estimators,oneof" json:"sort_by_estimator,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TrafficShapingRateRequest) Reset() {
	*x = TrafficShapingRateRequest{}
	mi := &file_proto_TrafficShapingMonitor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficShapingRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficShapingRateRequest) ProtoMessage() {}

func (x *TrafficShapingRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_TrafficShapingMonitor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficShapingRateRequest.ProtoReflect.Descriptor instead.
func (*TrafficShapingRateRequest) Descriptor() ([]byte, []int) {
	return file_proto_TrafficShapingMonitor_proto_rawDescGZIP(), []int{0}
}

func (x *TrafficShapingRateRequest) GetEstimators() []TrafficShapingRateRequest_Estimators {
	if x != nil {
		return x.Estimators
	}
	return nil
}

func (x *TrafficShapingRateRequest) GetIncludeTypes() []TrafficShapingRateRequest_EntityType {
	if x != nil {
		return x.IncludeTypes
	}
	return nil
}

func (x *TrafficShapingRateRequest) GetTopN() uint32 {
	if x != nil && x.TopN != nil {
		return *x.TopN
	}
	return 0
}

func (x *TrafficShapingRateRequest) GetSortByEstimator() TrafficShapingRateRequest_Estimators {
	if x != nil && x.SortByEstimator != nil {
		return *x.SortByEstimator
	}
	return TrafficShapingRateRequest_UNSPECIFIED
}

type TrafficShapingRateResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	// These are only filled if requested in RateRequest
	AppStats      []*AppRateEntry   `protobuf:"bytes,2,rep,name=app_stats,json=appStats,proto3" json:"app_stats,omitempty"`
	UserStats     []*UserRateEntry  `protobuf:"bytes,3,rep,name=user_stats,json=userStats,proto3" json:"user_stats,omitempty"`
	GroupStats    []*GroupRateEntry `protobuf:"bytes,4,rep,name=group_stats,json=groupStats,proto3" json:"group_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficShapingRateResponse) Reset() {
	*x = TrafficShapingRateResponse{}
	mi := &file_proto_TrafficShapingMonitor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficShapingRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficShapingRateResponse) ProtoMessage() {}

func (x *TrafficShapingRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_TrafficShapingMonitor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficShapingRateResponse.ProtoReflect.Descriptor instead.
func (*TrafficShapingRateResponse) Descriptor() ([]byte, []int) {
	return file_proto_TrafficShapingMonitor_proto_rawDescGZIP(), []int{1}
}

func (x *TrafficShapingRateResponse) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *TrafficShapingRateResponse) GetAppStats() []*AppRateEntry {
	if x != nil {
		return x.AppStats
	}
	return nil
}

func (x *TrafficShapingRateResponse) GetUserStats() []*UserRateEntry {
	if x != nil {
		return x.UserStats
	}
	return nil
}

func (x *TrafficShapingRateResponse) GetGroupStats() []*GroupRateEntry {
	if x != nil {
		return x.GroupStats
	}
	return nil
}

type AppRateEntry struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	AppName string                 `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	// CHANGE THIS: Add 'repeated'
	Stats         []*RateStats `protobuf:"bytes,2,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppRateEntry) Reset() {
	*x = AppRateEntry{}
	mi := &file_proto_TrafficShapingMonitor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppRateEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppRateEntry) ProtoMessage() {}

func (x *AppRateEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_TrafficShapingMonitor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppRateEntry.ProtoReflect.Descriptor instead.
func (*AppRateEntry) Descriptor() ([]byte, []int) {
	return file_proto_TrafficShapingMonitor_proto_rawDescGZIP(), []int{2}
}

func (x *AppRateEntry) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *AppRateEntry) GetStats() []*RateStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type UserRateEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Uid   uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// CHANGE THIS: Add 'repeated'
	Stats         []*RateStats `protobuf:"bytes,2,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRateEntry) Reset() {
	*x = UserRateEntry{}
	mi := &file_proto_TrafficShapingMonitor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRateEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRateEntry) ProtoMessage() {}

func (x *UserRateEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_TrafficShapingMonitor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRateEntry.ProtoReflect.Descriptor instead.
func (*UserRateEntry) Descriptor() ([]byte, []int) {
	return file_proto_TrafficShapingMonitor_proto_rawDescGZIP(), []int{3}
}

func (x *UserRateEntry) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UserRateEntry) GetStats() []*RateStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type GroupRateEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Gid   uint32                 `protobuf:"varint,1,opt,name=gid,proto3" json:"gid,omitempty"`
	// CHANGE THIS: Add 'repeated'
	Stats         []*RateStats `protobuf:"bytes,2,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupRateEntry) Reset() {
	*x = GroupRateEntry{}
	mi := &file_proto_TrafficShapingMonitor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupRateEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupRateEntry) ProtoMessage() {}

func (x *GroupRateEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_TrafficShapingMonitor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupRateEntry.ProtoReflect.Descriptor instead.
func (*GroupRateEntry) Descriptor() ([]byte, []int) {
	return file_proto_TrafficShapingMonitor_proto_rawDescGZIP(), []int{4}
}

func (x *GroupRateEntry) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *GroupRateEntry) GetStats() []*RateStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type RateStats struct {
	state              protoimpl.MessageState               `protogen:"open.v1"`
	Window             TrafficShapingRateRequest_Estimators `protobuf:"varint,1,opt,name=window,proto3,enum=eos.traffic_shaping.TrafficShapingRateRequest_Estimators" json:"window,omitempty"`
	BytesReadPerSec    float64                              `protobuf:"fixed64,2,opt,name=bytes_read_per_sec,json=bytesReadPerSec,proto3" json:"bytes_read_per_sec,omitempty"`
	BytesWrittenPerSec float64                              `protobuf:"fixed64,3,opt,name=bytes_written_per_sec,json=bytesWrittenPerSec,proto3" json:"bytes_written_per_sec,omitempty"`
	IopsRead           float64                              `protobuf:"fixed64,4,opt,name=iops_read,json=iopsRead,proto3" json:"iops_read,omitempty"`
	IopsWrite          float64                              `protobuf:"fixed64,5,opt,name=iops_write,json=iopsWrite,proto3" json:"iops_write,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RateStats) Reset() {
	*x = RateStats{}
	mi := &file_proto_TrafficShapingMonitor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateStats) ProtoMessage() {}

func (x *RateStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_TrafficShapingMonitor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateStats.ProtoReflect.Descriptor instead.
func (*RateStats) Descriptor() ([]byte, []int) {
	return file_proto_TrafficShapingMonitor_proto_rawDescGZIP(), []int{5}
}

func (x *RateStats) GetWindow() TrafficShapingRateRequest_Estimators {
	if x != nil {
		return x.Window
	}
	return TrafficShapingRateRequest_UNSPECIFIED
}

func (x *RateStats) GetBytesReadPerSec() float64 {
	if x != nil {
		return x.BytesReadPerSec
	}
	return 0
}

func (x *RateStats) GetBytesWrittenPerSec() float64 {
	if x != nil {
		return x.BytesWrittenPerSec
	}
	return 0
}

func (x *RateStats) GetIopsRead() float64 {
	if x != nil {
		return x.IopsRead
	}
	return 0
}

func (x *RateStats) GetIopsWrite() float64 {
	if x != nil {
		return x.IopsWrite
	}
	return 0
}

var File_proto_TrafficShapingMonitor_proto protoreflect.FileDescriptor

const file_proto_TrafficShapingMonitor_proto_rawDesc = "" +
	"\n" +
	"!proto/TrafficShapingMonitor.proto\x12\x13eos.traffic_shaping\"\xe4\x04\n" +
	"\x19TrafficShapingRateRequest\x12Y\n" +
	"\n" +
	"estimators\x18\x01 \x03(\x0e29.eos.traffic_shaping.TrafficShapingRateRequest.EstimatorsR\n" +
	"estimators\x12^\n" +
	"\rinclude_types\x18\x02 \x03(\x0e29.eos.traffic_shaping.TrafficShapingRateRequest.EntityTypeR\fincludeTypes\x12\x18\n" +
	"\x05top_n\x18\x03 \x01(\rH\x00R\x04topN\x88\x01\x01\x12j\n" +
	"\x11sort_by_estimator\x18\x04 \x01(\x0e29.eos.traffic_shaping.TrafficShapingRateRequest.EstimatorsH\x01R\x0fsortByEstimator\x88\x01\x01\"\x8f\x01\n" +
	"\n" +
	"Estimators\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSMA_5_SECONDS\x10\x01\x12\x11\n" +
	"\rSMA_1_MINUTES\x10\x02\x12\x11\n" +
	"\rSMA_5_MINUTES\x10\x03\x12\x11\n" +
	"\rEMA_5_SECONDS\x10\x04\x12\x11\n" +
	"\rEMA_1_MINUTES\x10\x05\x12\x11\n" +
	"\rEMA_5_MINUTES\x10\x06\"T\n" +
	"\n" +
	"EntityType\x12\x16\n" +
	"\x12ENTITY_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"ENTITY_APP\x10\x01\x12\x0e\n" +
	"\n" +
	"ENTITY_UID\x10\x02\x12\x0e\n" +
	"\n" +
	"ENTITY_GID\x10\x03B\b\n" +
	"\x06_top_nB\x14\n" +
	"\x12_sort_by_estimator\"\x88\x02\n" +
	"\x1aTrafficShapingRateResponse\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\x12>\n" +
	"\tapp_stats\x18\x02 \x03(\v2!.eos.traffic_shaping.AppRateEntryR\bappStats\x12A\n" +
	"\n" +
	"user_stats\x18\x03 \x03(\v2\".eos.traffic_shaping.UserRateEntryR\tuserStats\x12D\n" +
	"\vgroup_stats\x18\x04 \x03(\v2#.eos.traffic_shaping.GroupRateEntryR\n" +
	"groupStats\"_\n" +
	"\fAppRateEntry\x12\x19\n" +
	"\bapp_name\x18\x01 \x01(\tR\aappName\x124\n" +
	"\x05stats\x18\x02 \x03(\v2\x1e.eos.traffic_shaping.RateStatsR\x05stats\"W\n" +
	"\rUserRateEntry\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\x124\n" +
	"\x05stats\x18\x02 \x03(\v2\x1e.eos.traffic_shaping.RateStatsR\x05stats\"X\n" +
	"\x0eGroupRateEntry\x12\x10\n" +
	"\x03gid\x18\x01 \x01(\rR\x03gid\x124\n" +
	"\x05stats\x18\x02 \x03(\v2\x1e.eos.traffic_shaping.RateStatsR\x05stats\"\xfa\x01\n" +
	"\tRateStats\x12Q\n" +
	"\x06window\x18\x01 \x01(\x0e29.eos.traffic_shaping.TrafficShapingRateRequest.EstimatorsR\x06window\x12+\n" +
	"\x12bytes_read_per_sec\x18\x02 \x01(\x01R\x0fbytesReadPerSec\x121\n" +
	"\x15bytes_written_per_sec\x18\x03 \x01(\x01R\x12bytesWrittenPerSec\x12\x1b\n" +
	"\tiops_read\x18\x04 \x01(\x01R\biopsRead\x12\x1d\n" +
	"\n" +
	"iops_write\x18\x05 \x01(\x01R\tiopsWrite2\x80\x01\n" +
	"\x03Eos\x12y\n" +
	"\x12TrafficShapingRate\x12..eos.traffic_shaping.TrafficShapingRateRequest\x1a/.eos.traffic_shaping.TrafficShapingRateResponse\"\x000\x01B#Z!eos_traffic_shaping_monitor/protob\x06proto3"

var (
	file_proto_TrafficShapingMonitor_proto_rawDescOnce sync.Once
	file_proto_TrafficShapingMonitor_proto_rawDescData []byte
)

func file_proto_TrafficShapingMonitor_proto_rawDescGZIP() []byte {
	file_proto_TrafficShapingMonitor_proto_rawDescOnce.Do(func() {
		file_proto_TrafficShapingMonitor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_TrafficShapingMonitor_proto_rawDesc), len(file_proto_TrafficShapingMonitor_proto_rawDesc)))
	})
	return file_proto_TrafficShapingMonitor_proto_rawDescData
}

var file_proto_TrafficShapingMonitor_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_TrafficShapingMonitor_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_TrafficShapingMonitor_proto_goTypes = []any{
	(TrafficShapingRateRequest_Estimators)(0), // 0: eos.traffic_shaping.TrafficShapingRateRequest.Estimators
	(TrafficShapingRateRequest_EntityType)(0), // 1: eos.traffic_shaping.TrafficShapingRateRequest.EntityType
	(*TrafficShapingRateRequest)(nil),         // 2: eos.traffic_shaping.TrafficShapingRateRequest
	(*TrafficShapingRateResponse)(nil),        // 3: eos.traffic_shaping.TrafficShapingRateResponse
	(*AppRateEntry)(nil),                      // 4: eos.traffic_shaping.AppRateEntry
	(*UserRateEntry)(nil),                     // 5: eos.traffic_shaping.UserRateEntry
	(*GroupRateEntry)(nil),                    // 6: eos.traffic_shaping.GroupRateEntry
	(*RateStats)(nil),                         // 7: eos.traffic_shaping.RateStats
}
var file_proto_TrafficShapingMonitor_proto_depIdxs = []int32{
	0,  // 0: eos.traffic_shaping.TrafficShapingRateRequest.estimators:type_name -> eos.traffic_shaping.TrafficShapingRateRequest.Estimators
	1,  // 1: eos.traffic_shaping.TrafficShapingRateRequest.include_types:type_name -> eos.traffic_shaping.TrafficShapingRateRequest.EntityType
	0,  // 2: eos.traffic_shaping.TrafficShapingRateRequest.sort_by_estimator:type_name -> eos.traffic_shaping.TrafficShapingRateRequest.Estimators
	4,  // 3: eos.traffic_shaping.TrafficShapingRateResponse.app_stats:type_name -> eos.traffic_shaping.AppRateEntry
	5,  // 4: eos.traffic_shaping.TrafficShapingRateResponse.user_stats:type_name -> eos.traffic_shaping.UserRateEntry
	6,  // 5: eos.traffic_shaping.TrafficShapingRateResponse.group_stats:type_name -> eos.traffic_shaping.GroupRateEntry
	7,  // 6: eos.traffic_shaping.AppRateEntry.stats:type_name -> eos.traffic_shaping.RateStats
	7,  // 7: eos.traffic_shaping.UserRateEntry.stats:type_name -> eos.traffic_shaping.RateStats
	7,  // 8: eos.traffic_shaping.GroupRateEntry.stats:type_name -> eos.traffic_shaping.RateStats
	0,  // 9: eos.traffic_shaping.RateStats.window:type_name -> eos.traffic_shaping.TrafficShapingRateRequest.Estimators
	2,  // 10: eos.traffic_shaping.Eos.TrafficShapingRate:input_type -> eos.traffic_shaping.TrafficShapingRateRequest
	3,  // 11: eos.traffic_shaping.Eos.TrafficShapingRate:output_type -> eos.traffic_shaping.TrafficShapingRateResponse
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_TrafficShapingMonitor_proto_init() }
func file_proto_TrafficShapingMonitor_proto_init() {
	if File_proto_TrafficShapingMonitor_proto != nil {
		return
	}
	file_proto_TrafficShapingMonitor_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_TrafficShapingMonitor_proto_rawDesc), len(file_proto_TrafficShapingMonitor_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_TrafficShapingMonitor_proto_goTypes,
		DependencyIndexes: file_proto_TrafficShapingMonitor_proto_depIdxs,
		EnumInfos:         file_proto_TrafficShapingMonitor_proto_enumTypes,
		MessageInfos:      file_proto_TrafficShapingMonitor_proto_msgTypes,
	}.Build()
	File_proto_TrafficShapingMonitor_proto = out.File
	file_proto_TrafficShapingMonitor_proto_goTypes = nil
	file_proto_TrafficShapingMonitor_proto_depIdxs = nil
}
