// ----------------------------------------------------------------------------
// File: TrafficShaping.proto
// Author: Luis Antonio Obis Aparicio <luis.obis@cern.ch>
// ----------------------------------------------------------------------------

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/TrafficShaping.proto

// TODO: review package name

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrafficShapingService_StreamIoStats_FullMethodName = "/eos.ioshapping.TrafficShapingService/StreamIoStats"
)

// TrafficShapingServiceClient is the client API for TrafficShapingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrafficShapingServiceClient interface {
	// Bidirectional streaming: The FST opens a stream and pushes FstIoReport repeatedly.
	// The MGM can push back MgmIoResponse (limits/acks) asynchronously.
	StreamIoStats(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FstIoReport, MgmIoResponse], error)
}

type trafficShapingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrafficShapingServiceClient(cc grpc.ClientConnInterface) TrafficShapingServiceClient {
	return &trafficShapingServiceClient{cc}
}

func (c *trafficShapingServiceClient) StreamIoStats(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FstIoReport, MgmIoResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TrafficShapingService_ServiceDesc.Streams[0], TrafficShapingService_StreamIoStats_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FstIoReport, MgmIoResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrafficShapingService_StreamIoStatsClient = grpc.BidiStreamingClient[FstIoReport, MgmIoResponse]

// TrafficShapingServiceServer is the server API for TrafficShapingService service.
// All implementations must embed UnimplementedTrafficShapingServiceServer
// for forward compatibility.
type TrafficShapingServiceServer interface {
	// Bidirectional streaming: The FST opens a stream and pushes FstIoReport repeatedly.
	// The MGM can push back MgmIoResponse (limits/acks) asynchronously.
	StreamIoStats(grpc.BidiStreamingServer[FstIoReport, MgmIoResponse]) error
	mustEmbedUnimplementedTrafficShapingServiceServer()
}

// UnimplementedTrafficShapingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrafficShapingServiceServer struct{}

func (UnimplementedTrafficShapingServiceServer) StreamIoStats(grpc.BidiStreamingServer[FstIoReport, MgmIoResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamIoStats not implemented")
}
func (UnimplementedTrafficShapingServiceServer) mustEmbedUnimplementedTrafficShapingServiceServer() {}
func (UnimplementedTrafficShapingServiceServer) testEmbeddedByValue()                               {}

// UnsafeTrafficShapingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrafficShapingServiceServer will
// result in compilation errors.
type UnsafeTrafficShapingServiceServer interface {
	mustEmbedUnimplementedTrafficShapingServiceServer()
}

func RegisterTrafficShapingServiceServer(s grpc.ServiceRegistrar, srv TrafficShapingServiceServer) {
	// If the following call panics, it indicates UnimplementedTrafficShapingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrafficShapingService_ServiceDesc, srv)
}

func _TrafficShapingService_StreamIoStats_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TrafficShapingServiceServer).StreamIoStats(&grpc.GenericServerStream[FstIoReport, MgmIoResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrafficShapingService_StreamIoStatsServer = grpc.BidiStreamingServer[FstIoReport, MgmIoResponse]

// TrafficShapingService_ServiceDesc is the grpc.ServiceDesc for TrafficShapingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrafficShapingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "eos.ioshapping.TrafficShapingService",
	HandlerType: (*TrafficShapingServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamIoStats",
			Handler:       _TrafficShapingService_StreamIoStats_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/TrafficShaping.proto",
}

const (
	RateReportingService_GetRates_FullMethodName    = "/eos.ioshapping.RateReportingService/GetRates"
	RateReportingService_StreamRates_FullMethodName = "/eos.ioshapping.RateReportingService/StreamRates"
)

// RateReportingServiceClient is the client API for RateReportingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RateReportingServiceClient interface {
	// Unary: Get a single snapshot (e.g., for a CLI tool like 'eos io stat')
	GetRates(ctx context.Context, in *RateRequest, opts ...grpc.CallOption) (*RateReport, error)
	// Streaming: Get live updates (e.g., for a Web Dashboard / Grafana)
	StreamRates(ctx context.Context, in *RateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RateReport], error)
}

type rateReportingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRateReportingServiceClient(cc grpc.ClientConnInterface) RateReportingServiceClient {
	return &rateReportingServiceClient{cc}
}

func (c *rateReportingServiceClient) GetRates(ctx context.Context, in *RateRequest, opts ...grpc.CallOption) (*RateReport, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RateReport)
	err := c.cc.Invoke(ctx, RateReportingService_GetRates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rateReportingServiceClient) StreamRates(ctx context.Context, in *RateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RateReport], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RateReportingService_ServiceDesc.Streams[0], RateReportingService_StreamRates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RateRequest, RateReport]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RateReportingService_StreamRatesClient = grpc.ServerStreamingClient[RateReport]

// RateReportingServiceServer is the server API for RateReportingService service.
// All implementations must embed UnimplementedRateReportingServiceServer
// for forward compatibility.
type RateReportingServiceServer interface {
	// Unary: Get a single snapshot (e.g., for a CLI tool like 'eos io stat')
	GetRates(context.Context, *RateRequest) (*RateReport, error)
	// Streaming: Get live updates (e.g., for a Web Dashboard / Grafana)
	StreamRates(*RateRequest, grpc.ServerStreamingServer[RateReport]) error
	mustEmbedUnimplementedRateReportingServiceServer()
}

// UnimplementedRateReportingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRateReportingServiceServer struct{}

func (UnimplementedRateReportingServiceServer) GetRates(context.Context, *RateRequest) (*RateReport, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRates not implemented")
}
func (UnimplementedRateReportingServiceServer) StreamRates(*RateRequest, grpc.ServerStreamingServer[RateReport]) error {
	return status.Error(codes.Unimplemented, "method StreamRates not implemented")
}
func (UnimplementedRateReportingServiceServer) mustEmbedUnimplementedRateReportingServiceServer() {}
func (UnimplementedRateReportingServiceServer) testEmbeddedByValue()                              {}

// UnsafeRateReportingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RateReportingServiceServer will
// result in compilation errors.
type UnsafeRateReportingServiceServer interface {
	mustEmbedUnimplementedRateReportingServiceServer()
}

func RegisterRateReportingServiceServer(s grpc.ServiceRegistrar, srv RateReportingServiceServer) {
	// If the following call panics, it indicates UnimplementedRateReportingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RateReportingService_ServiceDesc, srv)
}

func _RateReportingService_GetRates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RateReportingServiceServer).GetRates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RateReportingService_GetRates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RateReportingServiceServer).GetRates(ctx, req.(*RateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RateReportingService_StreamRates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RateReportingServiceServer).StreamRates(m, &grpc.GenericServerStream[RateRequest, RateReport]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RateReportingService_StreamRatesServer = grpc.ServerStreamingServer[RateReport]

// RateReportingService_ServiceDesc is the grpc.ServiceDesc for RateReportingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RateReportingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "eos.ioshapping.RateReportingService",
	HandlerType: (*RateReportingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRates",
			Handler:    _RateReportingService_GetRates_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamRates",
			Handler:       _RateReportingService_StreamRates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/TrafficShaping.proto",
}
